name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: code-majestic
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push generated SVG to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Alpana Singh
          author_email: alpanasinghcs@gmail.com
          message: "chore: generate contribution snake"
          add: "dist/github-contribution-grid-snake.svg"


